apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edspace.fullname" . }}-env
  labels:
    {{- include "edspace.labels" . | nindent 4 }}
data:
  {{- include "edspace.envConfigData" . | nindent 2 }}
