apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edspace.fullname" . }}-env
  labels:
    {{- include "edspace.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "edspace.envSecretData" . | nindent 2 }}
